### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-aretomo#101]
I've got 2/8 tests failing with aretomo2-1.1.3 cuda121:

```
[   FAILED ] TestAreTomo2.test_align_01_excluded_views


Traceback (most recent call last):
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/gsharov/soft/scipion-em-plugins/scipion-em-aretomo/aretomo/tests/test_aretomo.py", line 141, in test_align_01_excluded_views
    self._run_test_align_01(importedTs, expectedDimsInterpTs,
  File "/home/gsharov/soft/scipion-em-plugins/scipion-em-aretomo/aretomo/tests/test_aretomo.py", line 185, in _run_test_align_01
    self.checkTiltSeries(getattr(prot, OUT_TS, None),
  File "/home/gsharov/soft/scipion-em-plugins/scipion-em-tomo/tomo/tests/test_base_centralized_layer.py", line 197, in checkTiltSeries
    self.checkTomoAcquisition(testAcqObj, tsAcq, tsId=tsId)
  File "/home/gsharov/soft/scipion-em-plugins/scipion-em-tomo/tomo/tests/test_base_centralized_layer.py", line 347, in checkTomoAcquisition
    self.assertAlmostEqual(testAcq.getTiltAxisAngle(), currentAcq.getTiltAxisAngle(), delta=0.5)
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 966, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 85.4368 != 84.5377 within 0.5 delta (0.8991000000000042 difference)


[   FAILED ] TestAreTomo2.test_align_02_excluded_views


Traceback (most recent call last):
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/gsharov/soft/scipion-em-plugins/scipion-em-aretomo/aretomo/tests/test_aretomo.py", line 290, in test_align_02_excluded_views
    self._run_test_align_02(inTsSet=importedTs,
  File "/home/gsharov/soft/scipion-em-plugins/scipion-em-aretomo/aretomo/tests/test_aretomo.py", line 324, in _run_test_align_02
    self.checkTiltSeries(getattr(prot, OUT_TS, None),
  File "/home/gsharov/soft/scipion-em-plugins/scipion-em-tomo/tomo/tests/test_base_centralized_layer.py", line 197, in checkTiltSeries
    self.checkTomoAcquisition(testAcqObj, tsAcq, tsId=tsId)
  File "/home/gsharov/soft/scipion-em-plugins/scipion-em-tomo/tomo/tests/test_base_centralized_layer.py", line 347, in checkTomoAcquisition
    self.assertAlmostEqual(testAcq.getTiltAxisAngle(), currentAcq.getTiltAxisAngle(), delta=0.5)
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 966, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 85.4368 != 84.5377 within 0.5 delta (0.8991000000000042 difference)
```

**Comment by JorMaister** [comment]
Hi, @azazellochg, they are working fine on my machine. I suppose this is the usual problem with the Cuda calculations regarding the graphics hardware, Linux distro, and so on... I may admit a higher tolerance for the tests, let's say 1 deg, and check. Are you ok with that?
