### ISSUE TITLE
Running areTomo with CUDA 10.2

### ISSUE THREAD

**Issue by albertmena** [scipion-em/scipion-em-aretomo#44]
Runnig the test with CUDA 10.2:
```
GGenCommonLine::Setup: 79:
	no kernel image is available for execution on the device

AreTomo_1.3.4_Cuda102_Feb22_2023: Util/CSimpleFuncs.cpp:75: void Util::CheckCudaError(const char*): Assertion `0' failed.
Aborted (core dumped)
Traceback (most recent call last):
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
    self._run()
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 252, in _run
    resultFiles = self._runFunc()
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _runFunc
    return self._func(*self._args)
  File "/home/agarcia/scipion3/software/em/scipion-em-aretomo/aretomo/protocols/protocol_aretomo.py", line 350, in runAreTomoStep
    self.runJob(program, param, env=Plugin.getEnviron())
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1487, in runJob
    self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
    process.runJob(log, programName, params,
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 55, in runJob
    return runCommand(command, env, cwd)
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 70, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' /home/agarcia/scipion3/software/em/aretomo-1.3.4/bin/AreTomo_1.3.4_Cuda102_Feb22_2023 -InMrc Runs/000079_ProtAreTomoAlignRecon/tmp/a/BBa.mrc -OutMrc Runs/000079_ProtAreTomoAlignRecon/extra/a/BBa.mrc -AngFile Runs/000079_ProtAreTomoAlignRecon/tmp/a/BBa.tlt -VolZ 0 -OutBin 2 -FlipInt 0 -FlipVol 0 -PixSize 20.2 -Kv 300.0 -Cs 2.7 -Defoc 0 -DarkTol 0.7 -Gpu 0 -Align 1 -TiltAxis -12.5 0 -TiltCor 0 -AlignZ 180 -Sart 15 5 ' returned non-zero exit status 134.
Protocol failed: Command ' /home/agarcia/scipion3/software/em/aretomo-1.3.4/bin/AreTomo_1.3.4_Cuda102_Feb22_2023 -InMrc Runs/000079_ProtAreTomoAlignRecon/tmp/a/BBa.mrc -OutMrc Runs/000079_ProtAreTomoAlignRecon/extra/a/BBa.mrc -AngFile Runs/000079_ProtAreTomoAlignRecon/tmp/a/BBa.tlt -VolZ 0 -OutBin 2 -FlipInt 0 -FlipVol 0 -PixSize 20.2 -Kv 300.0 -Cs 2.7 -Defoc 0 -DarkTol 0.7 -Gpu 0 -Align 1 -TiltAxis -12.5 0 -TiltCor 0 -AlignZ 180 -Sart 15 5 ' returned non-zero exit status 134.

```

**Comment by azazellochg** [comment]
Hi @albertmena , this looks like a binary problem to me, not related to the plugin . Let me see tomorrow if I can find an old GPU that supports cuda 10. I would suggest to report that error to Shawn, the developer

**Comment by albertmena** [comment]
Ok, thanks, I can run aretomo in other machine

**Comment by azazellochg** [comment]
Hi, I have just run the test successfully with cuda 10.2 (AreTomo_1.3.4_Cuda102_Feb22_2023) on a Tesla T4 card

**Comment by albertmena** [comment]
I've test it with CUDA 11.4 and works. Not sure about the reason of fail in 10.2, but we could close the issue.
Thanks!
