### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-aretomo#84]
devel branch, aretomo2 1.1.2
```
[   FAILED ] TestAreTomo.test_align_02


Traceback (most recent call last):
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
yield
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
self._callTestMethod(testMethod)
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
method()
File "/public/EM/Scipion/scipion-dev/scipion-em-plugins/scipion-em-aretomo/aretomo/tests/test_protocols_aretomo.py", line 191, in test_align_02
self.checkTiltSeries(getattr(prot, OUT_TS, None),
File "/public/EM/Scipion/scipion-dev/scipion-em-plugins/scipion-em-tomo/tomo/tests/test_base_centralized_layer.py", line 198, in checkTiltSeries
self.checkObjectEnabled(ti, isExcludedView, tsId, ind)
File "/public/EM/Scipion/scipion-dev/scipion-em-plugins/scipion-em-tomo/tomo/tests/test_base_centralized_layer.py", line 799, in checkObjectEnabled
self.assertFalse(enb, msg='TsId = %s: %s %i was expected not to be Enabled' % (tsId, objType, ind))
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 759, in assertFalse
raise self.failureException(msg)
AssertionError: True is not false : TsId = TS_54: Tilt image 0 was expected not to be Enabled
```

**Comment by JorMaister** [comment]
Hi, @azazellochg,
The exclusion of views based on the dark tolerance does not work in aretomo2-1.1.2. I opened an issue in their report some time ago, but it has not been answered yet. Personally, I'd remove that version from the available ones and let aretomo2-1.0.0 be the default one until aretomo3 is integrated. What do you think? And you, @pconesa?

**Comment by azazellochg** [comment]
Hi,

I was thinking the same. We have to either change the default binary or
change the test :)

**Comment by pconesa** [comment]
If latest binary is not functional I vote for removing it.

**Comment by azazellochg** [comment]
Maybe they fixed smth in aretomo3. I don't know if aretomo2 is developed anymore
